TENX_ALN_MODE: local
TENX_ALN_CORES: 1
TENX_ALN_MEM: 6
TENX_DATA_PATH: /mnt/disks/data
TENX_LONGRANGER_SOFTWARE_URL: @LONGRANGER_SOFTWARE_URL@
TENX_NOTIFICATIONS_SLACK: @NOTIFICATION@
TENX_REMOTE_URL: @REMOTE_DATA_URL@
TENX_REMOTE_REFS_URL: @REMOTE_REFS_URL@
