TENX_ASM_CORES: @ALN_CORES@
TENX_ASM_MEM: @ALN_MEM@
TENX_DATA_PATH: /mnt/disks/data
TENX_SUPERNOVA_SOFTWARE_URL: @LONGRANGER_SOFTWARE_URL@
TENX_NOTIFICATIONS_SLACK: @NOTIFICATION@
TENX_REMOTE_URL: @REMOTE_DATA_URL@
TENX_REMOTE_REFS_URL: @REMOTE_REFS_URL@
