TENX_ALN_MODE: @ALN_MODE@
TENX_ALN_CORES: @ALN_CORES@
TENX_ALN_MEM: @ALN_MEM@
TENX_ALN_PARAMS: @ALN_PARAMS@
TENX_ALN_VCMODE: freebayes
TENX_CROMWELL_PATH: /apps/cromwell
TENX_CROMWELL_VERSION: 55
TENX_DATA_PATH: /mnt/disks/data
TENX_LONGRANGER_SOFTWARE_URL: @LONGRANGER_SOFTWARE_URL@
TENX_NOTIFICATIONS_SLACK: @NOTIFICATION@
TENX_REMOTE_URL: @REMOTE_DATA_URL@
TENX_REMOTE_REFS_URL: @REMOTE_REFS_URL@
