TENX_DATA_PATH: /mnt/disks/data
TENX_SUPERNOVA_SOFTWARE_URL: @SUPERNOVA_SOFTWARE_URL@
TENX_ASM_PARAMS: @ASM_PARAMS@
TENX_MACHINE_TYPE: @MACHINE_TYPE@
TENX_NOTIFICATIONS_SLACK: @NOTIFICATION@
TENX_REMOTE_URL: @REMOTE_DATA_URL@
TENX_CROMWELL_PATH: /apps/cromwell
TENX_CROMWELL_VERSION: 50
