#!/bin/bash
#
#SBATCH --job-name=DL_READS
#SBATCH --output=%j.out

set -e

[ -z "${1}" ] && echo "No sample given!" && exit 1
export TENX_SAMPLE="${1}"
source /apps/tenx-scripts/tenxrc
echo "Fetching ${TENX_SAMPLE} fastqs from the object store..."
mkdir -p "${TENX_RDS_PATH}"
cd "${TENX_RDS_PATH}"
echo "Checking for sample reads remote URL..."
gsutil ls "${TENX_RDS_URL}"
gsutil -m rsync -r "${TENX_RDS_URL}/" .
echo "Fetching fastqs from the object store...OK"
