#!/bin/bash
#
#SBATCH --job-name=LR-WGS
#SBATCH --out=%J.out
#SBATCH --mem=6G

set -e

[ -z "${1}" ] && echo "No sample given!" && exit 1
[ -z "${2}" ] && echo "No reference given!" && exit 1
export TENX_SAMPLE="${1}"
export TENX_REFNAME="${2}"
source /apps/tenx-scripts/tenxrc

mkdir -p "${TENX_ALN_PATH}"
cd "${TENX_ALN_PATH}"
source /apps/longranger/sourceme.bash
TENX_LR_PARAMS=--id="${TENX_SAMPLE} --sample=${TENX_SAMPLE} --fastqs=${TENX_RDS_PATH} --reference=${TENX_REF_PATH} --jobmode=slurm --uiport=18080 --localmem=6 --localcores=1"
if [ ! -z "${3}" ]; then
    longranger wgs "${TENX_LR_PARAMS} --vcmode=${3}"
else
    longranger align "${TENX_LR_PARAMS}"
fi
