#!/bin/bash

set -o errexit

source /apps/tenx-scripts/tenxrc

TENX_LR_USAGE="
USAGE:
  run-lr <SAMPLE> <REFERENCE> [VCMODE]

SCRIPTS LOCATION:
  /apps/tenx-scripts/

DATA LOCATION:
  ${DATA_PATH}
  
"

[ -z "${1}" ] && echo "No sample given!${TENX_LR_USAGE}" && exit 1
[ -z "${2}" ] && echo "No reference given!${TENX_LR_USAGE}" && exit 1

TENX_SCRIPTS_PATH=/apps/tenx-scripts
"${TENX_SCRIPTS_PATH}/dl-reads" ${1}
"${TENX_SCRIPTS_PATH}/dl-ref" ${2}

if [ -z "${3}" ]; then
    "${TENX_SCRIPTS_PATH}/lr-aln" "${1}" "${2}"
else
    "${TENX_SCRIPTS_PATH}/lr-aln" "${1}" "${2}" "${3}"
fi
"${TENX_SCRIPTS_PATH}/run-duration.py" "${1}"
"${TENX_SCRIPTS_PATH}/ul-aln" "${1}"
