#!/bin/bash

set -o errexit

if [ ! -z "${TENX_SAMPLE}" ]; then
    # Local PATHs
    TENX_SAMPLE_PATH="@DATA_PATH@/${TENX_SAMPLE}"
    TENX_ALN_PATH="${TENX_SAMPLE_PATH}/alignment"
    TENX_ASM_PATH="${TENX_SAMPLE_PATH}/assembly"
    TENX_RDS_PATH="${TENX_SAMPLE_PATH}/reads"

    # Remote URLs
    TENX_SAMPLE_URL="@REMOTE_DATA_URL@/${TENX_SAMPLE}"
    TENX_ASM_URL="${TENX_SAMPLE_URL}/assembly"
    TENX_ALN_URL="${TENX_SAMPLE_URL}/alignment"
    TENX_RDS_URL="${TENX_SAMPLE_URL}/reads"
fi

TENX_REFS_PATH=@DATA_PATH@/references
if [ ! -z "${TENX_REFNAME}" ]; then
    TENX_REF_TGZ="${TENX_REFNAME}.tar.gz"
    TENX_REF_PATH="@DATA_PATH@/references/${TENX_REFNAME}"
    TENX_REF_TGZ_PATH="@DATA_PATH@/references/${TENX_REF_TGZ}"
    TENX_REF_URL="@REMOTE_DATA_URL@/references/${TENX_REF_TGZ}"
fi

