#!/bin/bash

set -o errexit

TENX_SCRIPTS_PATH=/apps/tenx-scripts
source /apps/tenx-scripts/tenxrc

TENX_SN_USAGE="
USAGE:
  run-supernova <SAMPLE>

SCRIPTS LOCATION:
  ${TENX_SCRIPTS_PATH}

DATA LOCATION:
  ${TENX_DATA_PATH}
  
"

[ -z "${1}" ] && echo "No sample given!${TENX_SN_USAGE}" && exit 1

"${TENX_SCRIPTS_PATH}/dl-reads" ${1}
"${TENX_SCRIPTS_PATH}/sn-asm" "${1}"
"${TENX_SCRIPTS_PATH}/sn-mkoutput" "${1}"
"${TENX_SCRIPTS_PATH}/run-duration.py" "${TENX_ASM_PATH}"
"${TENX_SCRIPTS_PATH}/ul-asm" "${1}"
