#!/bin/bash

set -e

[ -z "${1}" ] && echo "No sample given!" && exit 1
export TENX_SAMPLE="${1}"

source /apps/tenx-scripts/tenxrc
source /apps/supernova/sourceme.bash
mkdir -p "${TENX_SAMPLE_PATH}"
cd "${TENX_SAMPLE_PATH}"
supernova run --id=assembly --fastqs="${TENX_RDS_PATH}" --uiport=18080 --nodebugmem --localcores=50 --localmem=400
